### ISSUE TITLE
Error messages in Step 3

### ISSUE THREAD

**Issue by jungminchoilab** [jcarrotzhang/LoLoPicker#1]
Hello,

Thanks for sharing your code. I am encountering the following error in the last step.
I would be grateful if you can look into this.

ps. I am using 35 panel of normals and wonder if you could recommend the number for the parameter, --SNPcutoff. 

Best,
Jungmin

```
(vir_env) [jc2545@c13n09 FTC609]$ ls -tlr
total 195968
-rw-r--r-- 1 jc2545 lifton  90461887 Jan  4 06:14 raw_somatic_varants.txt
-rw-r--r-- 1 jc2545 lifton 109997077 Jan  4 08:34 control_stats.txt

(vir_env) [jc2545@c13n09 lolopicker]$ python ~/programs/LoLoPicker/lolopicker/scripts/LoLoPicker_stats.py -o FTC609
Traceback (most recent call last):
  File "/home/jc2545/programs/LoLoPicker/lolopicker/scripts/LoLoPicker_stats.py", line 45, in <module>
    (inputvariant, statsfile, rejectfile, correction, basecov, SNPcut) = main(sys.argv[1:])
  File "/home/jc2545/programs/LoLoPicker/lolopicker/scripts/LoLoPicker_stats.py", line 42, in main
    return inputvariant, statsfile, rejectfile, correction, int(basecov), int(SNPcut)
UnboundLocalError: local variable 'correction' referenced before assignment 
```

**Comment by jcarrotzhang** [comment]
Hi Jungmin,

Thank you for using LoLoPicker. The newer version requires --method option
to specify the multiple testing correction (Bonferroni or FDR). If you are
using lolopicker to filter variants from mutect for example, FDR is
recommended. I updated README on github.

I think you could use --SNPcutoff 2. Let me know how it goes!

Best,
Jian

**Comment by jungminchoilab** [comment]
Hi Jian,

Great, it worked. Thanks again for your prompt response.
I am interested in identifying potential FFPE-specific artifacts (C:G>T:A) so was looking at the "reject_calls.txt" file and found "info" column there.
Is there a flag indicating FFPE-related artifacts here?

Best,
Jungmin

**Comment by jcarrotzhang** [comment]
Hi Jungmin,

I don't flag possible FFPE artifacts but I could include this information
for improvement. You could perhaps search C:G>T:A type of variants in the
rejected outputs. Or you could run a mutational signature analysis to look
at the fraction of potential FFPE errors (it usually looks like aging
signature but the level is much higher).

Best,
Jian

**Comment by jungminchoilab** [comment]
Hi Jian,

I think it will be helpful. As you suggested, I will look for the C:G>T:A variants in the rejected files for now. Indeed, I found a predominant signature (looking like Signature 1 - aging) but wanted to pinpoint the artifact variants so we do not need to exclude the samples.

Best,
Jungmin
