### ISSUE TITLE
panel of FFPE normals

### ISSUE THREAD

**Issue by mmaitenat** [jcarrotzhang/LoLoPicker#3]
Hi!
It may be a silly question, but it was not clear to me from the manuscript. Should the panel of normals correspond to the same patient from whom we are providing the tumor sample, could be any sample from the same experiment (and hence processed the same way) or could instead be any normal FFPE sample?

Many thanks,

Maitena.

**Comment by jcarrotzhang** [comment]
Ideally samples from the same experiment, but any normal FFPE samples would work.

Best,
Jian

**Comment by mmaitenat** [comment]
Thanks!!
