### ISSUE TITLE
Error: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by master-noddy** [jcarrotzhang/LoLoPicker#5]
Every time I am loading the proper files I am getting this error, please someone address this issue and get back to me as soon as possible.

(virtual_env) -bash-4.2$ time python lolopicker/scripts/LoLoPicker_somatic.py -t ~/BAMS_for_exp_31_12_2019/114T_mergeFiltered.bam -n ~/BAMS_for_exp_31_12_2019/114N_mergeFiltered.bam -r ~/Refseq/NCBI37_WO_DECOY.fa -b ~/Truseq_45MB_bed.wo_chrM.bed -o ~/LoLoPicker/  
  File "lolopicker/scripts/LoLoPicker_somatic.py", line 18
    print 'usage: python LoLoPicker_somatic.py -t <tumor.bam> -n <normal.bam> -r <reference.fa> -b <intervals.bed> -o <outputpath>'
                                                                                                                                  ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('usage: python LoLoPicker_somatic.py -t <tumor.bam> -n <normal.bam> -r <reference.fa> -b <intervals.bed> -o <outputpath>')?

**Comment by master-noddy** [comment]
If I am giving the files provided in the zip file, then also I am getting the same error. 

python lolopicker/scripts/LoLoPicker_somatic.py -t 'LoLoPicker_example/blood.bam' -n 'LoLoPicker_example/control1.bam' -r 'LoLoPicker_example/region.fa' -b 'LoLoPicker_example/example_interval.bed' -o 'LoLoPicker_example/output/'
  File "lolopicker/scripts/LoLoPicker_somatic.py", line 18
    print 'usage: python LoLoPicker_somatic.py -t <tumor.bam> -n <normal.bam> -r <reference.fa> -b <intervals.bed> -o <outputpath>'
                                                                                                                                  ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('usage: python LoLoPicker_somatic.py -t <tumor.bam> -n <normal.bam> -r <reference.fa> -b <intervals.bed> -o <outputpath>')?

**Comment by jcarrotzhang** [comment]
Hi Nalesh,

Are you using Python 2.7? Print in Python 3+ is different.

Best,
Jian

**Comment by master-noddy** [comment]
I am using Python 3.6.9

**Comment by jcarrotzhang** [comment]
Sorry you need to use Python2.7.

**Comment by master-noddy** [comment]
That issue is solved.
Thank you so much ! @jcarrotzhang
